---
version: '3.7'
services:
  iotabot:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - DB=${DB}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GBF_BOT_SERVER_PORT=${GBF_BOT_SERVER_PORT}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - LOGIN=${LOGIN}
      - OSU_TOKEN=${OSU_TOKEN}
      - PASSW=${PASSW}
    labels:
      "autoheal": "true"
    ports:
      - "8090:8090"
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/status"]
      interval: 60s
      timeout: 3s
      retries: 10
    volumes:
      - '/run/postgresql:/run/postgresql'
    container_name: iotabot
    restart: always

  pp:
    build:
      context: ./osu_tools
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    labels:
      "autoheal": "true"
    container_name: osu_tools_wrapper
    restart: always

  autoheal:
    restart: always
    privileged: true
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_INTERVAL=120
      - CURL_TIMEOUT=30
      - AUTOHEAL_START_PERIOD=120
