services:
  iotabot:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "80:80"
    volumes:
      - '/db_data:/db_data'
    container_name: bot
    hostname: bot
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13.16-alpine
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osu
    container_name: db
    hostname: db
    ports:
      - "5433:5432"

  pp_calc:
    build:
      context: ./pp_calculator
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    container_name: pp_calc
    hostname: pp_calc
    restart: always


volumes:
  db_data:
