---
version: '3.7'
services:
  iotabot:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      "autoheal": "true"
    ports:
      - 8090:8090
      - 5432:5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/status"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - '/run/postgresql:/run/postgresql'
    image: iotabot
    restart: always

  autoheal:
    privileged: true
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
