services:
  iotabot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/db_data:/db_data'
    container_name: bot
    restart: always
    command: bash -c "alembic upgrade head && python -u main.py"
    depends_on:
      - db

  db:
    image: postgres:13.16-alpine
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osu
    container_name: db
    ports:
      - "5432:5432"

  pp_calc:
    build:
      context: ./pp_calculator
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    container_name: pp_calc
    restart: always


volumes:
  db_data:
