"""set mods optional column in scores model

Revision ID: 06bc1e563e5c
Revises: 3a88d9cd61bd
Create Date: 2024-11-17 19:28:40.708387

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '06bc1e563e5c'
down_revision: Union[str, None] = '3a88d9cd61bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'mods', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'mods', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
