"""add status field to beatmap

Revision ID: 21d8f46cee1d
Revises: 782ca3dee914
Create Date: 2024-11-21 01:00:58.159867

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21d8f46cee1d'
down_revision: Union[str, None] = '782ca3dee914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beatmap', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beatmap', 'status')
    # ### end Alembic commands ###
