"""remove beatmap constraint for highscores

Revision ID: 2cb1c3028540
Revises: 6f477d288952
Create Date: 2024-12-07 12:15:39.448080

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2cb1c3028540'
down_revision: Union[str, None] = '6f477d288952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('highscores_beatmap_id_fkey', 'highscores', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('highscores_beatmap_id_fkey', 'highscores', 'beatmap', ['beatmap_id'], ['beatmap_id'])
    # ### end Alembic commands ###
