"""lazer column is false by default

Revision ID: 3a88d9cd61bd
Revises: 8d3482f35cc7
Create Date: 2024-11-17 18:32:10.937441

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '3a88d9cd61bd'
down_revision: Union[str, None] = '8d3482f35cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
