"""rename random columns in discorduser table

Revision ID: 494019237f63
Revises: ee7f04ef578a
Create Date: 2024-11-19 17:18:21.452366

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '494019237f63'
down_revision: Union[str, None] = 'ee7f04ef578a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_user', sa.Column('discord_user_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('discord_user_osu_user_id_fkey', 'discord_user', type_='foreignkey')
    op.create_foreign_key(None, 'discord_user', 'user', ['user_id'], ['user_id'])
    op.drop_column('discord_user', 'osu_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_user', sa.Column('osu_user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'discord_user', type_='foreignkey')
    op.create_foreign_key('discord_user_osu_user_id_fkey', 'discord_user', 'user', ['osu_user_id'], ['user_id'])
    op.drop_column('discord_user', 'discord_user_id')
    # ### end Alembic commands ###
