"""update score model to the latest osu api version

Revision ID: 4faa8f0ccbbd
Revises: d113fe4bb524
Create Date: 2024-11-17 18:12:51.853618

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4faa8f0ccbbd'
down_revision: Union[str, None] = 'd113fe4bb524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('meh', sa.BigInteger(), nullable=True))
    op.add_column('scores', sa.Column('ok', sa.BigInteger(), nullable=True))
    op.add_column('scores', sa.Column('great', sa.BigInteger(), nullable=True))
    op.add_column('scores', sa.Column('miss', sa.BigInteger(), nullable=True))
    op.drop_column('scores', 'count_100')
    op.drop_column('scores', 'count_geki')
    op.drop_column('scores', 'count_miss')
    op.drop_column('scores', 'count_50')
    op.drop_column('scores', 'count_300')
    op.drop_column('scores', 'count_katu')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('count_katu', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('count_300', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('count_50', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('count_miss', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('count_geki', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('scores', sa.Column('count_100', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('scores', 'miss')
    op.drop_column('scores', 'great')
    op.drop_column('scores', 'ok')
    op.drop_column('scores', 'meh')
    # ### end Alembic commands ###
