"""remove highscores table

Revision ID: 5e5980a2a393
Revises: 2cb1c3028540
Create Date: 2024-12-28 13:31:17.435738

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e5980a2a393'
down_revision: Union[str, None] = '2cb1c3028540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highscores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscores',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('beatmap_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('placement', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='highscores_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='highscores_pkey')
    )
    # ### end Alembic commands ###
