"""add highscores table

Revision ID: 6f477d288952
Revises: cd1e2de262f6
Create Date: 2024-12-07 11:47:21.158920

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f477d288952'
down_revision: Union[str, None] = 'cd1e2de262f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('beatmap_id', sa.BigInteger(), nullable=False),
    sa.Column('placement', sa.BigInteger(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['beatmap_id'], ['beatmap.beatmap_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highscores')
    # ### end Alembic commands ###
