"""eik nx su relationships

Revision ID: 782ca3dee914
Revises: aa2a1f747a45
Create Date: 2024-11-19 17:29:40.758063

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '782ca3dee914'
down_revision: Union[str, None] = 'aa2a1f747a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
