"""add lazer column to scores model

Revision ID: 8d3482f35cc7
Revises: 4faa8f0ccbbd
Create Date: 2024-11-17 18:22:27.543720

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d3482f35cc7'
down_revision: Union[str, None] = '4faa8f0ccbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('lazer', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'lazer')
    # ### end Alembic commands ###
