"""add human readable columns for beatmapset

Revision ID: 8f7555cf3205
Revises: 06bc1e563e5c
Create Date: 2024-11-19 16:38:17.253971

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f7555cf3205'
down_revision: Union[str, None] = '06bc1e563e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beatmapset', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('beatmapset', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beatmapset', 'title')
    op.drop_column('beatmapset', 'artist')
    # ### end Alembic commands ###
