"""make user columns match osu api nullability

Revision ID: 9608b0bd1ba2
Revises: 5e5980a2a393
Create Date: 2026-08-04 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9608b0bd1ba2'
down_revision: Union[str, None] = '5e5980a2a393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'previous_usernames', existing_type=sa.String(), nullable=True)
    op.alter_column('user', 'play_time', existing_type=sa.BigInteger(), nullable=True)
    op.alter_column('user', 'pp', existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'pp', existing_type=sa.Float(), nullable=False)
    op.alter_column('user', 'play_time', existing_type=sa.BigInteger(), nullable=False)
    op.alter_column('user', 'previous_usernames', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###
