"""add discorduser table

Revision ID: 96f43c0ed5d8
Revises: f960751db8d1
Create Date: 2024-11-19 17:06:13.497742

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96f43c0ed5d8'
down_revision: Union[str, None] = 'f960751db8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('osu_user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['osu_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_user')
    # ### end Alembic commands ###
