"""eik nx su relationships

Revision ID: aa2a1f747a45
Revises: fa92d9e07adc
Create Date: 2024-11-19 17:26:45.464919

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'aa2a1f747a45'
down_revision: Union[str, None] = 'fa92d9e07adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
