"""change created_at to ended_at for score model

Revision ID: d113fe4bb524
Revises: f91cd89ae59f
Create Date: 2024-11-17 16:45:07.755183

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd113fe4bb524'
down_revision: Union[str, None] = 'f91cd89ae59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('score_ended_at', sa.DateTime(), nullable=True))
    op.drop_column('scores', 'score_created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('score_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('scores', 'score_ended_at')
    # ### end Alembic commands ###
