"""add relationship for user for discorduser

Revision ID: ee7f04ef578a
Revises: 96f43c0ed5d8
Create Date: 2024-11-19 17:16:06.716302

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ee7f04ef578a'
down_revision: Union[str, None] = '96f43c0ed5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
