"""initial db

Revision ID: f91cd89ae59f
Revises: 
Create Date: 2024-10-21 19:22:22.075967

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f91cd89ae59f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'beatmapset',
        sa.Column('beatmapset_id', sa.BigInteger(), nullable=False),
        sa.Column('artist_unicode', sa.String(), nullable=False),
        sa.Column('creator', sa.String(), nullable=False),
        sa.Column('title_unicode', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('beatmapset_id'),
    )
    op.create_table(
        'user',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('avatar_url', sa.String(), nullable=False),
        sa.Column('country_code', sa.String(), nullable=False),
        sa.Column('previous_usernames', sa.String(), nullable=False),
        sa.Column('global_rank', sa.BigInteger(), nullable=True),
        sa.Column('country_rank', sa.BigInteger(), nullable=True),
        sa.Column('hit_accuracy', sa.Float(), nullable=False),
        sa.Column('play_count', sa.BigInteger(), nullable=False),
        sa.Column('play_time', sa.BigInteger(), nullable=False),
        sa.Column('pp', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_table(
        'beatmap',
        sa.Column('beatmap_id', sa.BigInteger(), nullable=False),
        sa.Column('beatmapset_id', sa.BigInteger(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('bpm', sa.Float(), nullable=True),
        sa.Column('max_combo', sa.BigInteger(), nullable=True),
        sa.Column('difficulty_rating', sa.Float(), nullable=False),
        sa.Column('total_length', sa.BigInteger(), nullable=False),
        sa.Column('ar', sa.Float(), nullable=False),
        sa.Column('cs', sa.Float(), nullable=False),
        sa.Column('drain', sa.Float(), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=False),
        sa.Column('cover_url', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['beatmapset_id'],
            ['beatmapset.beatmapset_id'],
        ),
        sa.PrimaryKeyConstraint('beatmap_id'),
    )
    op.create_table(
        'tracking_channels',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('channel_id', sa.BigInteger(), nullable=False),
        sa.Column('channel_name', sa.String(), nullable=False),
        sa.Column('guild_id', sa.BigInteger(), nullable=False),
        sa.Column('guild_name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.user_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'scores',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('beatmap_id', sa.BigInteger(), nullable=False),
        sa.Column('score_created_at', sa.DateTime(), nullable=False),
        sa.Column('max_combo', sa.BigInteger(), nullable=False),
        sa.Column('mods', sa.String(), nullable=False),
        sa.Column('pp', sa.Float(), nullable=True),
        sa.Column('rank', sa.String(), nullable=False),
        sa.Column('accuracy', sa.Float(), nullable=True),
        sa.Column('count_50', sa.BigInteger(), nullable=True),
        sa.Column('count_100', sa.BigInteger(), nullable=True),
        sa.Column('count_300', sa.BigInteger(), nullable=True),
        sa.Column('count_geki', sa.BigInteger(), nullable=True),
        sa.Column('count_katu', sa.BigInteger(), nullable=True),
        sa.Column('count_miss', sa.BigInteger(), nullable=True),
        sa.Column('passed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['beatmap_id'],
            ['beatmap.beatmap_id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.user_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('tracking_channels')
    op.drop_table('beatmap')
    op.drop_table('user')
    op.drop_table('beatmapset')
    # ### end Alembic commands ###
