"""add discorduser table

Revision ID: f960751db8d1
Revises: 8f7555cf3205
Create Date: 2024-11-19 16:55:49.367137

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f960751db8d1'
down_revision: Union[str, None] = '8f7555cf3205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
