"""fix relationship for users for discordusers

Revision ID: fa92d9e07adc
Revises: 77f68bc5e8c8
Create Date: 2024-11-19 17:21:20.149222

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fa92d9e07adc'
down_revision: Union[str, None] = '77f68bc5e8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
